In [2]:
import pandas as pd
df = pd.read_csv('diabetes_dataset.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [3]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
columns_to_check = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

for column in columns_to_check:
    print(f"{column}: {(df[column] == 0).sum()}")

Glucose: 5
BloodPressure: 35
SkinThickness: 227
Insulin: 374
BMI: 11


In [5]:
import numpy as np
columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

import numpy as np

columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

df[columns] = df[columns].replace(0, np.nan)
df[columns] = df[columns].fillna(df[columns].median())
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
X = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=100, random_state=42, solver='lbfgs')

In [10]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)
print("Predicted Classes:")
print(y_pred[:10])


Predicted Classes:
[0 0 0 0 0 0 0 0 1 1]


In [11]:
print("\nPredicted Probabilities:")
print(y_prob[:10])


Predicted Probabilities:
[[0.72650648 0.27349352]
 [0.83274552 0.16725448]
 [0.89278831 0.10721169]
 [0.84589992 0.15410008]
 [0.53748186 0.46251814]
 [0.56562556 0.43437444]
 [0.98601508 0.01398492]
 [0.6160686  0.3839314 ]
 [0.4244803  0.5755197 ]
 [0.23804933 0.76195067]]


In [12]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.7532467532467533

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[82, 17],
       [21, 34]])

In [14]:
from sklearn.metrics import precision_score, recall_score, f1_score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Precision: {precision:.3f}")
print(f"Recall: {recall:.3f}")
print(f"F1 Score: {f1:.3f}")

Precision: 0.667
Recall: 0.618
F1 Score: 0.642


In [15]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154



In [17]:
from sklearn.metrics import roc_auc_score
auc = roc_auc_score(y_test, y_prob[:,1])
auc

0.82277318640955

In [27]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=42, max_depth=5)
dt_model.fit(X_train, y_train)
dt_pred = dt_model.predict(X_test)
dt_prob = dt_model.predict_proba(X_test)

In [29]:


print("Accuracy:", accuracy_score(y_test, dt_pred))
print("\nConfusion Matrix")
print(confusion_matrix(y_test, dt_pred))

print("\nClassification Report")
print(classification_report(y_test, dt_pred))

print("\nROC-AUC:", roc_auc_score(y_test, dt_prob[:,1]))

Accuracy: 0.7272727272727273

Confusion Matrix
[[70 29]
 [13 42]]

Classification Report
              precision    recall  f1-score   support

           0       0.84      0.71      0.77        99
           1       0.59      0.76      0.67        55

    accuracy                           0.73       154
   macro avg       0.72      0.74      0.72       154
weighted avg       0.75      0.73      0.73       154


ROC-AUC: 0.8231404958677686


In [30]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)
rf_prob = rf_model.predict_proba(X_test)


In [31]:
print("Accuracy:", accuracy_score(y_test, dt_pred))
print("\nConfusion Matrix")
print(confusion_matrix(y_test, dt_pred))

print("\nClassification Report")
print(classification_report(y_test, dt_pred))

print("\nROC-AUC:", roc_auc_score(y_test, dt_prob[:,1]))

Accuracy: 0.7272727272727273

Confusion Matrix
[[70 29]
 [13 42]]

Classification Report
              precision    recall  f1-score   support

           0       0.84      0.71      0.77        99
           1       0.59      0.76      0.67        55

    accuracy                           0.73       154
   macro avg       0.72      0.74      0.72       154
weighted avg       0.75      0.73      0.73       154


ROC-AUC: 0.8231404958677686


In [32]:
print(dt_model)

print(rf_model)

DecisionTreeClassifier(max_depth=5, random_state=42)
RandomForestClassifier(random_state=42)


In [33]:
print(dt_pred[:10])
print(rf_pred[:10])

[1 0 0 0 0 1 0 1 1 1]
[1 0 0 0 1 1 0 1 1 1]


In [35]:
print((dt_pred == rf_pred).sum())
print(len(dt_pred))


123
154


In [41]:
from sklearn.model_selection import GridSearchCV

parameters = {
    'C': [0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs'],
    'max_iter': [500, 1000]
}

grid = GridSearchCV(
    LogisticRegression(random_state=42),
    parameters,
    cv=5,
    scoring='accuracy',      # Change to 'accuracy' if you want highest accuracy
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best Cross Validation Score:", grid.best_score_)

Best Parameters: {'C': 1, 'max_iter': 500, 'solver': 'liblinear'}
Best Cross Validation Score: 0.7687724910035986


In [42]:
best_model = grid.best_estimator_

y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nROC-AUC:", roc_auc_score(y_test, y_prob[:,1]))

Accuracy: 0.7532467532467533

Confusion Matrix
[[82 17]
 [21 34]]

Classification Report
              precision    recall  f1-score   support

           0       0.80      0.83      0.81        99
           1       0.67      0.62      0.64        55

    accuracy                           0.75       154
   macro avg       0.73      0.72      0.73       154
weighted avg       0.75      0.75      0.75       154


ROC-AUC: 0.82277318640955
